# Generated by Django 5.0.6 on 2024-06-18 19:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AddResponse",
            new_name="GPTTraining",
        ),
    ]
